export type GoalTier = "minor" | "major";

export type ProgressGoal = {
  id: string;
  tier: GoalTier;
  title: string;
  detail?: string;
};

export const PROGRESS_GOALS: ProgressGoal[] = [
  { id: "m01", tier: "minor", title: "Break a pot and collect the drop", detail: "Any vase or pot drop" },
  { id: "m02", tier: "minor", title: "Break a silver pot", detail: "Grab the guaranteed XP" },
  { id: "m03", tier: "minor", title: "First XP shard level-up", detail: "Trigger a level-up" },
  { id: "m04", tier: "minor", title: "Reach a small gold threshold", detail: "From pots, chests, or mobs" },
  { id: "m05", tier: "minor", title: "Bank silver coins", detail: "Confirm silver coins are added" },
  { id: "m06", tier: "minor", title: "Open first paid chest", detail: "Pay gold and pick an item" },
  { id: "m07", tier: "minor", title: "Open a free gold chest", detail: "No gold required" },
  { id: "m08", tier: "minor", title: "Stop paid chests when price spikes", detail: "Avoid the gold death spiral" },
  { id: "m09", tier: "minor", title: "Capture a Sanctuary/Altar", detail: "Choose the best of 3 stats" },
  { id: "m10", tier: "minor", title: "Capture a Golden Altar", detail: "Legendary-only boosts" },
  { id: "m11", tier: "minor", title: "Activate a Moai statue", detail: "Pick an item from the set" },
  { id: "m12", tier: "minor", title: "Use a Moai reroll", detail: "Upgrade the offering" },
  { id: "m13", tier: "minor", title: "Complete a Trial (Swords)", detail: "Clear elites and claim the crate" },
  { id: "m14", tier: "minor", title: "Trigger a Magnet shrine", detail: "Vacuum coins and XP" },
  { id: "m15", tier: "minor", title: "Use a dropped buff well", detail: "Shield, clock, rage, magnet, nuke" },
  { id: "m16", tier: "minor", title: "Buy from a vendor", detail: "Any shop purchase" },
  { id: "m17", tier: "minor", title: "Buy from yellow-hat vendor", detail: "Legendary-only shop" },
  { id: "m18", tier: "minor", title: "Use Shady Guy exchange", detail: "Coins for random loot" },
  { id: "m19", tier: "minor", title: "Finish a Charge Shrine", detail: "Stay in zone until done" },
  { id: "m20", tier: "minor", title: "Activate Greed Sanctuary", detail: "Harder, better rewards" },
  { id: "m21", tier: "minor", title: "Activate Boss Curse statue", detail: "Extra boss pressure" },
  { id: "m22", tier: "minor", title: "Kill an elite cleanly", detail: "Crown elite without big HP loss" },
  { id: "m23", tier: "minor", title: "Kill a gold skeleton", detail: "Collect big gold payout" },
  { id: "m24", tier: "minor", title: "Kill a silver skeleton", detail: "Collect big XP payout" },
  { id: "m25", tier: "minor", title: "Pick a build-correct upgrade", detail: "Level-up choice matches plan" },
  { id: "m26", tier: "minor", title: "Level a weapon once", detail: "Confirm upgrades apply" },
  { id: "m27", tier: "minor", title: "Weapon to level 5", detail: "In one run" },
  { id: "m28", tier: "minor", title: "Weapon to level 10", detail: "In one run" },
  { id: "m29", tier: "minor", title: "Tome to level 5", detail: "Basic scaling online" },
  { id: "m30", tier: "minor", title: "Stack enough speed to kite", detail: "Kite a dense swarm" },
  { id: "m31", tier: "minor", title: "30s circle-kite vs boss", detail: "Clean movement, no panic" },
  { id: "m32", tier: "minor", title: "Dodge spike-line telegraph", detail: "Red marker to spike line" },
  { id: "m33", tier: "minor", title: "Bait a tracking attack", detail: "Change direction using terrain" },
  { id: "m34", tier: "minor", title: "Survive knockback chaos", detail: "Keep positioning control" },
  { id: "m35", tier: "minor", title: "Defeat a stage boss", detail: "Enter the portal correctly" },
  { id: "m36", tier: "minor", title: "Activate boss portal on F1-2", detail: "Spawn control" },
  { id: "m37", tier: "minor", title: "Kill the 7:00 boss", detail: "Timed boss handling" },
  { id: "m38", tier: "minor", title: "Kill the 2:00 boss", detail: "Timed boss handling" },
  { id: "m39", tier: "minor", title: "Survive Floor 1 timer", detail: "10 minutes" },
  { id: "m40", tier: "minor", title: "Survive Floor 2 timer", detail: "9 minutes" },
  { id: "m41", tier: "minor", title: "Survive Floor 3 timer", detail: "8 minutes" },
  { id: "m42", tier: "minor", title: "Vacuum XP after boss", detail: "Use the XP magnet moment" },
  { id: "m43", tier: "minor", title: "Open a cage with a golden key", detail: "Key management" },
  { id: "m44", tier: "minor", title: "Trigger Suspicious Bush and live", detail: "Disengage safely" },
  { id: "m45", tier: "minor", title: "Trigger Boss Generator and live", detail: "Survive the burst" },
  { id: "m46", tier: "minor", title: "Use desert tornado safely", detail: "Airborne then land clean" },
  { id: "m47", tier: "minor", title: "Kill while airborne", detail: "During special movement" },
  { id: "m48", tier: "minor", title: "Clone an item with Microwave", detail: "Respect rarity trade rules" },
  { id: "m49", tier: "minor", title: "No-hit loop of interactables", detail: "Altar to Trial to Chest" },
  { id: "m50", tier: "minor", title: "End run via portal", detail: "Clean termination" },

  { id: "M01", tier: "major", title: "Defeat Lil Bark", detail: "Forest Tier 1 boss" },
  { id: "M02", tier: "major", title: "Clear Forest T2 Stage 1", detail: "Enter portal to Stage 2" },
  { id: "M03", tier: "major", title: "Clear Forest T2 Stage 2", detail: "Unlock Forest Tier 3" },
  { id: "M04", tier: "major", title: "Complete Forest Tier 3 run", detail: "Reach ultimate boss" },
  { id: "M05", tier: "major", title: "Defeat Bark Vader", detail: "Forest Tier 3 boss" },
  { id: "M06", tier: "major", title: "Bark Vader with weapon disable", detail: "Only starting weapon" },
  { id: "M07", tier: "major", title: "Bark Vader pylon phases", detail: "Destroy pylons fast" },
  { id: "M08", tier: "major", title: "Win with Boss Curse active", detail: "Extra bosses pressure" },
  { id: "M09", tier: "major", title: "Unlock Desert via CL4NK", detail: "Reach Forest T2 Stage 2" },
  { id: "M10", tier: "major", title: "Unlock Revolver", detail: "7,500 enemies total" },
  { id: "M11", tier: "major", title: "Defeat Anubis", detail: "Desert boss" },
  { id: "M12", tier: "major", title: "Unlock Desert Tier 2", detail: "Complete first Desert boss" },
  { id: "M13", tier: "major", title: "Unlock Desert Tier 3", detail: "Complete Desert T2 Stage 2" },
  { id: "M14", tier: "major", title: "Clear Desert Tier 3 run", detail: "Finish boss sequence" },
  { id: "M15", tier: "major", title: "Defeat hidden boss Bush", detail: "Unlock Bush character" },
  { id: "M16", tier: "major", title: "Defeat hidden boss Bandit", detail: "Unlock Bandit rewards" },
  { id: "M17", tier: "major", title: "Defeat all 6 bosses", detail: "3 Forest, Anubis, 2 hidden" },
  { id: "M18", tier: "major", title: "Unlock XP Tome", detail: "Break 20 pots in one run" },
  { id: "M19", tier: "major", title: "Unlock Cursed Tome", detail: "Stage boss under 5 min" },
  { id: "M20", tier: "major", title: "Unlock Chaos Tome", detail: "Charge all shrines in T3 run" },
  { id: "M21", tier: "major", title: "Unlock Attraction Tome", detail: "Use Succ Shrine 8 times" },
  { id: "M22", tier: "major", title: "Unlock Armor Tome", detail: "5,000 kills as Sir Oofie" },
  { id: "M23", tier: "major", title: "Unlock Bloody Tome", detail: "12,500 kills total" },
  { id: "M24", tier: "major", title: "Unlock Duration Tome", detail: "Axe to level 10" },
  { id: "M25", tier: "major", title: "Unlock Thorns Tome", detail: "Block 250 hits with Aegis" },
  { id: "M26", tier: "major", title: "Unlock Quantity Tome", detail: "Fire 5,000 projectiles" },
  { id: "M27", tier: "major", title: "Obtain Luck Tome", detail: "Ultra-rare drop" },
  { id: "M28", tier: "major", title: "Reach tome level 99", detail: "Late-game scaling cap" },
  { id: "M29", tier: "major", title: "Reach weapon level 40", detail: "Late-game weapon cap" },
  { id: "M30", tier: "major", title: "Beat final boss under 10 min", detail: "Floor 3 boss arena" },
  { id: "M31", tier: "major", title: "Unlock Boss Buster", detail: "Stage boss under 30s" },
  { id: "M32", tier: "major", title: "Unlock Bob (Dead)", detail: "Survive Final Swarm 2 min" },
  { id: "M33", tier: "major", title: "Unlock Chonkplate", detail: "Reach 500 max HP" },
  { id: "M34", tier: "major", title: "Unlock Bloody Cleaver", detail: "Level 50 as Vlad" },
  { id: "M35", tier: "major", title: "Unlock Cursed Doll", detail: "Die 10 times" },
  { id: "M36", tier: "major", title: "Unlock Echo Shard", detail: "XP Tome to level 8" },
  { id: "M37", tier: "major", title: "Unlock Eagle Claw", detail: "10,000 kills as Birdo" },
  { id: "M38", tier: "major", title: "Unlock Dragonfire", detail: "4,000 fire kills" },
  { id: "M39", tier: "major", title: "Unlock Brass Knuckles", detail: "5,000 Sword kills" },
  { id: "M40", tier: "major", title: "Unlock +2 stat roll reward", detail: "Complete 3 Trials" },
  { id: "M41", tier: "major", title: "Activate all radios", detail: "Unlock music customization" },
  { id: "M42", tier: "major", title: "Execute Microwave clone build", detail: "Rarity-matched trades" },
  { id: "M43", tier: "major", title: "Build a chest economy route", detail: "Stop at the right price" },
  { id: "M44", tier: "major", title: "Win an Aura-centered run", detail: "S-tier 360 damage" },
  { id: "M45", tier: "major", title: "Win a Dice-centered run", detail: "Dicehead scaling crit" },
  { id: "M46", tier: "major", title: "Win an Aegis-centered run", detail: "Shield and counter play" },
  { id: "M47", tier: "major", title: "Win a Katana run", detail: "High-mobility kiting" },
  { id: "M48", tier: "major", title: "Win a Dexecutioner run", detail: "Execute scaling" },
  { id: "M49", tier: "major", title: "Post a leaderboard score", detail: "Top-100 or verified run" },
  { id: "M50", tier: "major", title: "Earn all 102 achievements", detail: "100% Steam completion" },
];

export const PROGRESS_GOALS_META = {
  minorCount: PROGRESS_GOALS.filter((g) => g.tier === "minor").length,
  majorCount: PROGRESS_GOALS.filter((g) => g.tier === "major").length,
};
